"""Smoke tests for src/apprentice/cli/serve.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_cli_serve():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.cli.serve")
    assert mod is not None

def test_serve_main_is_callable():
    """Function serve_main exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.cli.serve")
    fn = getattr(mod, "serve_main", None)
    assert fn is not None, "'serve_main' not found in apprentice.cli.serve"
    assert callable(fn)
