"""Smoke tests for src/apprentice/audit_log_adapter.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_audit_log_adapter():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.audit_log_adapter")
    assert mod is not None
