"""Smoke tests for src/apprentice/data_models.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_data_models():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.data_models")
    assert mod is not None

def test_create_task_request_is_callable():
    """Function create_task_request exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.data_models")
    fn = getattr(mod, "create_task_request", None)
    assert fn is not None, "'create_task_request' not found in apprentice.data_models"
    assert callable(fn)

def test_create_task_response_is_callable():
    """Function create_task_response exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.data_models")
    fn = getattr(mod, "create_task_response", None)
    assert fn is not None, "'create_task_response' not found in apprentice.data_models"
    assert callable(fn)

def test_create_confidence_snapshot_is_callable():
    """Function create_confidence_snapshot exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.data_models")
    fn = getattr(mod, "create_confidence_snapshot", None)
    assert fn is not None, "'create_confidence_snapshot' not found in apprentice.data_models"
    assert callable(fn)

def test_create_budget_state_is_callable():
    """Function create_budget_state exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.data_models")
    fn = getattr(mod, "create_budget_state", None)
    assert fn is not None, "'create_budget_state' not found in apprentice.data_models"
    assert callable(fn)

def test_record_cost_is_callable():
    """Function record_cost exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.data_models")
    fn = getattr(mod, "record_cost", None)
    assert fn is not None, "'record_cost' not found in apprentice.data_models"
    assert callable(fn)

def test_create_audit_entry_is_callable():
    """Function create_audit_entry exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.data_models")
    fn = getattr(mod, "create_audit_entry", None)
    assert fn is not None, "'create_audit_entry' not found in apprentice.data_models"
    assert callable(fn)

def test_create_sampling_decision_is_callable():
    """Function create_sampling_decision exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.data_models")
    fn = getattr(mod, "create_sampling_decision", None)
    assert fn is not None, "'create_sampling_decision' not found in apprentice.data_models"
    assert callable(fn)

def test_create_training_example_is_callable():
    """Function create_training_example exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.data_models")
    fn = getattr(mod, "create_training_example", None)
    assert fn is not None, "'create_training_example' not found in apprentice.data_models"
    assert callable(fn)

def test_create_comparison_pair_is_callable():
    """Function create_comparison_pair exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.data_models")
    fn = getattr(mod, "create_comparison_pair", None)
    assert fn is not None, "'create_comparison_pair' not found in apprentice.data_models"
    assert callable(fn)

def test_create_model_version_is_callable():
    """Function create_model_version exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.data_models")
    fn = getattr(mod, "create_model_version", None)
    assert fn is not None, "'create_model_version' not found in apprentice.data_models"
    assert callable(fn)

def test_serialize_model_is_callable():
    """Function serialize_model exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.data_models")
    fn = getattr(mod, "serialize_model", None)
    assert fn is not None, "'serialize_model' not found in apprentice.data_models"
    assert callable(fn)

def test_deserialize_model_is_callable():
    """Function deserialize_model exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.data_models")
    fn = getattr(mod, "deserialize_model", None)
    assert fn is not None, "'deserialize_model' not found in apprentice.data_models"
    assert callable(fn)

def test_validate_model_is_callable():
    """Function validate_model exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.data_models")
    fn = getattr(mod, "validate_model", None)
    assert fn is not None, "'validate_model' not found in apprentice.data_models"
    assert callable(fn)

def test_get_model_json_schema_is_callable():
    """Function get_model_json_schema exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.data_models")
    fn = getattr(mod, "get_model_json_schema", None)
    assert fn is not None, "'get_model_json_schema' not found in apprentice.data_models"
    assert callable(fn)
