"""Smoke tests for src/apprentice/middleware.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_middleware():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.middleware")
    assert mod is not None
