"""Smoke tests for src/apprentice/report_generator/models.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_report_generator_models():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.report_generator.models")
    assert mod is not None
