"""Smoke tests for src/apprentice/phase_manager.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_phase_manager():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.phase_manager")
    assert mod is not None

def test_compute_phase_is_callable():
    """Function compute_phase exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.phase_manager")
    fn = getattr(mod, "compute_phase", None)
    assert fn is not None, "'compute_phase' not found in apprentice.phase_manager"
    assert callable(fn)

def test_validate_thresholds_is_callable():
    """Function validate_thresholds exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.phase_manager")
    fn = getattr(mod, "validate_thresholds", None)
    assert fn is not None, "'validate_thresholds' not found in apprentice.phase_manager"
    assert callable(fn)

def test_evaluate_is_callable():
    """Function evaluate exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.phase_manager")
    fn = getattr(mod, "evaluate", None)
    assert fn is not None, "'evaluate' not found in apprentice.phase_manager"
    assert callable(fn)

def test_get_task_phase_is_callable():
    """Function get_task_phase exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.phase_manager")
    fn = getattr(mod, "get_task_phase", None)
    assert fn is not None, "'get_task_phase' not found in apprentice.phase_manager"
    assert callable(fn)

def test_get_task_state_is_callable():
    """Function get_task_state exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.phase_manager")
    fn = getattr(mod, "get_task_state", None)
    assert fn is not None, "'get_task_state' not found in apprentice.phase_manager"
    assert callable(fn)

def test_get_transition_history_is_callable():
    """Function get_transition_history exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.phase_manager")
    fn = getattr(mod, "get_transition_history", None)
    assert fn is not None, "'get_transition_history' not found in apprentice.phase_manager"
    assert callable(fn)

def test_reset_task_is_callable():
    """Function reset_task exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.phase_manager")
    fn = getattr(mod, "reset_task", None)
    assert fn is not None, "'reset_task' not found in apprentice.phase_manager"
    assert callable(fn)
