"""Smoke tests for src/apprentice/sampling_scheduler.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_sampling_scheduler():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.sampling_scheduler")
    assert mod is not None

def test_exponential_decay_is_callable():
    """Function exponential_decay exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.sampling_scheduler")
    fn = getattr(mod, "exponential_decay", None)
    assert fn is not None, "'exponential_decay' not found in apprentice.sampling_scheduler"
    assert callable(fn)

def test_linear_decay_is_callable():
    """Function linear_decay exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.sampling_scheduler")
    fn = getattr(mod, "linear_decay", None)
    assert fn is not None, "'linear_decay' not found in apprentice.sampling_scheduler"
    assert callable(fn)

def test_step_decay_is_callable():
    """Function step_decay exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.sampling_scheduler")
    fn = getattr(mod, "step_decay", None)
    assert fn is not None, "'step_decay' not found in apprentice.sampling_scheduler"
    assert callable(fn)
