"""Smoke tests for src/apprentice/task_registry.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_task_registry():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.task_registry")
    assert mod is not None

def test_get_task_is_callable():
    """Function get_task exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.task_registry")
    fn = getattr(mod, "get_task", None)
    assert fn is not None, "'get_task' not found in apprentice.task_registry"
    assert callable(fn)

def test_task_names_is_callable():
    """Function task_names exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.task_registry")
    fn = getattr(mod, "task_names", None)
    assert fn is not None, "'task_names' not found in apprentice.task_registry"
    assert callable(fn)
