"""Smoke tests for src/apprentice/audit_log.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_audit_log():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.audit_log")
    assert mod is not None
