"""Smoke tests for src/apprentice/cli/cli_models.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_cli_cli_models():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.cli.cli_models")
    assert mod is not None
