"""Smoke tests for src/apprentice/cli/init_wizard.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_cli_init_wizard():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.cli.init_wizard")
    assert mod is not None

def test_run_wizard_is_callable():
    """Function run_wizard exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.cli.init_wizard")
    fn = getattr(mod, "run_wizard", None)
    assert fn is not None, "'run_wizard' not found in apprentice.cli.init_wizard"
    assert callable(fn)
