"""Smoke tests for src/apprentice/feedback_collector.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_feedback_collector():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.feedback_collector")
    assert mod is not None
