"""Smoke tests for src/apprentice/router.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_router():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.router")
    assert mod is not None

def test_compute_routing_action_is_callable():
    """Function compute_routing_action exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.router")
    fn = getattr(mod, "compute_routing_action", None)
    assert fn is not None, "'compute_routing_action' not found in apprentice.router"
    assert callable(fn)

def test_build_audit_entry_is_callable():
    """Function build_audit_entry exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.router")
    fn = getattr(mod, "build_audit_entry", None)
    assert fn is not None, "'build_audit_entry' not found in apprentice.router"
    assert callable(fn)
