"""Smoke tests for src/apprentice/external_interfaces.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_external_interfaces():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.external_interfaces")
    assert mod is not None

def test_map_remote_error_is_callable():
    """Function map_remote_error exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.external_interfaces")
    fn = getattr(mod, "map_remote_error", None)
    assert fn is not None, "'map_remote_error' not found in apprentice.external_interfaces"
    assert callable(fn)

def test_map_local_unavailable_is_callable():
    """Function map_local_unavailable exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.external_interfaces")
    fn = getattr(mod, "map_local_unavailable", None)
    assert fn is not None, "'map_local_unavailable' not found in apprentice.external_interfaces"
    assert callable(fn)

def test_map_local_success_to_response_is_callable():
    """Function map_local_success_to_response exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.external_interfaces")
    fn = getattr(mod, "map_local_success_to_response", None)
    assert fn is not None, "'map_local_success_to_response' not found in apprentice.external_interfaces"
    assert callable(fn)

def test_map_remote_response_is_callable():
    """Function map_remote_response exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.external_interfaces")
    fn = getattr(mod, "map_remote_response", None)
    assert fn is not None, "'map_remote_response' not found in apprentice.external_interfaces"
    assert callable(fn)

def test_create_remote_adapter_is_callable():
    """Function create_remote_adapter exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.external_interfaces")
    fn = getattr(mod, "create_remote_adapter", None)
    assert fn is not None, "'create_remote_adapter' not found in apprentice.external_interfaces"
    assert callable(fn)

def test_create_local_adapter_is_callable():
    """Function create_local_adapter exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.external_interfaces")
    fn = getattr(mod, "create_local_adapter", None)
    assert fn is not None, "'create_local_adapter' not found in apprentice.external_interfaces"
    assert callable(fn)
