"""Smoke tests for src/apprentice/apprentice_class.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_apprentice_class():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.apprentice_class")
    assert mod is not None
