"""Smoke tests for src/apprentice/evaluators.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_evaluators():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.evaluators")
    assert mod is not None

def test_clamp_score_is_callable():
    """Function clamp_score exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.evaluators")
    fn = getattr(mod, "clamp_score", None)
    assert fn is not None, "'clamp_score' not found in apprentice.evaluators"
    assert callable(fn)

def test_cosine_similarity_is_callable():
    """Function cosine_similarity exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.evaluators")
    fn = getattr(mod, "cosine_similarity", None)
    assert fn is not None, "'cosine_similarity' not found in apprentice.evaluators"
    assert callable(fn)

def test_create_evaluator_is_callable():
    """Function create_evaluator exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.evaluators")
    fn = getattr(mod, "create_evaluator", None)
    assert fn is not None, "'create_evaluator' not found in apprentice.evaluators"
    assert callable(fn)
