"""Smoke tests for src/apprentice/cli/cli.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_cli_cli():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.cli.cli")
    assert mod is not None

def test_configure_logging_is_callable():
    """Function configure_logging exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.cli.cli")
    fn = getattr(mod, "configure_logging", None)
    assert fn is not None, "'configure_logging' not found in apprentice.cli.cli"
    assert callable(fn)

def test_parse_args_is_callable():
    """Function parse_args exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.cli.cli")
    fn = getattr(mod, "parse_args", None)
    assert fn is not None, "'parse_args' not found in apprentice.cli.cli"
    assert callable(fn)

def test_load_config_is_callable():
    """Function load_config exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.cli.cli")
    fn = getattr(mod, "load_config", None)
    assert fn is not None, "'load_config' not found in apprentice.cli.cli"
    assert callable(fn)

def test_resolve_input_is_callable():
    """Function resolve_input exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.cli.cli")
    fn = getattr(mod, "resolve_input", None)
    assert fn is not None, "'resolve_input' not found in apprentice.cli.cli"
    assert callable(fn)

def test_format_output_is_callable():
    """Function format_output exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.cli.cli")
    fn = getattr(mod, "format_output", None)
    assert fn is not None, "'format_output' not found in apprentice.cli.cli"
    assert callable(fn)

def test_execute_run_is_callable():
    """Function execute_run exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.cli.cli")
    fn = getattr(mod, "execute_run", None)
    assert fn is not None, "'execute_run' not found in apprentice.cli.cli"
    assert callable(fn)

def test_execute_status_is_callable():
    """Function execute_status exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.cli.cli")
    fn = getattr(mod, "execute_status", None)
    assert fn is not None, "'execute_status' not found in apprentice.cli.cli"
    assert callable(fn)

def test_execute_report_is_callable():
    """Function execute_report exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.cli.cli")
    fn = getattr(mod, "execute_report", None)
    assert fn is not None, "'execute_report' not found in apprentice.cli.cli"
    assert callable(fn)

def test_execute_pii_ingest_is_callable():
    """Function execute_pii_ingest exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.cli.cli")
    fn = getattr(mod, "execute_pii_ingest", None)
    assert fn is not None, "'execute_pii_ingest' not found in apprentice.cli.cli"
    assert callable(fn)

def test_execute_pii_evaluate_is_callable():
    """Function execute_pii_evaluate exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.cli.cli")
    fn = getattr(mod, "execute_pii_evaluate", None)
    assert fn is not None, "'execute_pii_evaluate' not found in apprentice.cli.cli"
    assert callable(fn)

def test_execute_ingest_is_callable():
    """Function execute_ingest exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.cli.cli")
    fn = getattr(mod, "execute_ingest", None)
    assert fn is not None, "'execute_ingest' not found in apprentice.cli.cli"
    assert callable(fn)

def test_main_is_callable():
    """Function main exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.cli.cli")
    fn = getattr(mod, "main", None)
    assert fn is not None, "'main' not found in apprentice.cli.cli"
    assert callable(fn)
