"""Smoke tests for src/apprentice/local_model_server.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_local_model_server():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.local_model_server")
    assert mod is not None
