"""Smoke tests for src/apprentice/report_generator/core.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_report_generator_core():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.report_generator.core")
    assert mod is not None
