"""Smoke tests for src/apprentice/config_loader.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_config_loader():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.config_loader")
    assert mod is not None

def test_get_unresolved_vars_is_callable():
    """Function get_unresolved_vars exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.config_loader")
    fn = getattr(mod, "get_unresolved_vars", None)
    assert fn is not None, "'get_unresolved_vars' not found in apprentice.config_loader"
    assert callable(fn)

def test_resolve_env_var_is_callable():
    """Function resolve_env_var exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.config_loader")
    fn = getattr(mod, "resolve_env_var", None)
    assert fn is not None, "'resolve_env_var' not found in apprentice.config_loader"
    assert callable(fn)

def test_load_config_is_callable():
    """Function load_config exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.config_loader")
    fn = getattr(mod, "load_config", None)
    assert fn is not None, "'load_config' not found in apprentice.config_loader"
    assert callable(fn)

def test_validate_cross_field_constraints_is_callable():
    """Function validate_cross_field_constraints exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.config_loader")
    fn = getattr(mod, "validate_cross_field_constraints", None)
    assert fn is not None, "'validate_cross_field_constraints' not found in apprentice.config_loader"
    assert callable(fn)
