"""Smoke tests for src/apprentice/rolling_window.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_rolling_window():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.rolling_window")
    assert mod is not None
