"""Smoke tests for src/apprentice/budget_manager.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_budget_manager():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.budget_manager")
    assert mod is not None
