"""Smoke tests for src/apprentice/config_and_registry.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_config_and_registry():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.config_and_registry")
    assert mod is not None

def test_validate_model_is_callable():
    """Function validate_model exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.config_and_registry")
    fn = getattr(mod, "validate_model", None)
    assert fn is not None, "'validate_model' not found in apprentice.config_and_registry"
    assert callable(fn)
