"""Smoke tests for examples/wos_client.py (auto-generated by pact adopt)."""

import pytest

def test_import_examples_wos_client():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("examples.wos_client")
    assert mod is not None

def test_main_is_callable():
    """Function main exists and is callable."""
    import importlib
    mod = importlib.import_module("examples.wos_client")
    fn = getattr(mod, "main", None)
    assert fn is not None, "'main' not found in examples.wos_client"
    assert callable(fn)
