"""Smoke tests for src/apprentice/model_validator.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_model_validator():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.model_validator")
    assert mod is not None
