"""Interactive setup wizard for Apprentice.

Guides the user through creating an apprentice.yaml config file.
Uses only input() and print() — no external TUI dependencies.
"""

import os
import sys
from pathlib import Path


def _prompt(label: str, default: str = "") -> str:
    """Prompt user with optional default value."""
    if default:
        raw = input(f"  {label} [{default}]: ").strip()
        return raw if raw else default
    else:
        while True:
            raw = input(f"  {label}: ").strip()
            if raw:
                return raw
            print("    (required)")


def _prompt_choice(label: str, choices: list[str], default: str = "") -> str:
    """Prompt user to choose from a list."""
    choices_str = "/".join(choices)
    if default:
        raw = input(f"  {label} [{choices_str}] ({default}): ").strip()
        return raw if raw in choices else default
    else:
        while True:
            raw = input(f"  {label} [{choices_str}]: ").strip()
            if raw in choices:
                return raw
            print(f"    Must be one of: {choices_str}")


def _prompt_multiline(label: str) -> str:
    """Prompt for multiline input, ending with a blank line."""
    print(f"  {label} (end with blank line):")
    lines = []
    while True:
        line = input("    ")
        if not line.strip():
            break
        lines.append(line)
    return "\n".join(lines)


def run_wizard(output_path: str = "./apprentice.yaml") -> str:
    """Run the interactive setup wizard.

    Returns the path to the generated config file.
    """
    print()
    print("=" * 60)
    print("  Apprentice Setup Wizard")
    print("=" * 60)
    print()

    # Step 1: Task Definition
    print("Step 1: Task Definition")
    print("-" * 40)
    task_name = _prompt("Task name (snake_case)", "classify_ticket")
    description = _prompt("Description", "Classify support tickets")

    prompt_template = _prompt_multiline("Prompt template")
    if not prompt_template:
        prompt_template = (
            "Classify the following input.\n"
            "Return JSON with the appropriate fields.\n\n"
            "Input: {text}"
        )

    input_fields = _prompt("Input fields (comma-sep)", "text")
    output_fields = _prompt("Output fields (comma-sep)", "category, priority")
    evaluator_type = _prompt_choice(
        "Evaluator",
        ["exact_match", "semantic_similarity", "llm_judge", "regex_match", "json_schema_match"],
        "exact_match",
    )

    # Parse match fields from output fields
    output_field_list = [f.strip() for f in output_fields.split(",") if f.strip()]
    match_fields_str = _prompt(
        "Match fields (comma-sep)",
        ", ".join(output_field_list),
    )
    match_field_list = [f.strip() for f in match_fields_str.split(",") if f.strip()]

    print()

    # Step 2: Remote Provider
    print("Step 2: Remote Provider")
    print("-" * 40)
    provider = _prompt("Provider", "anthropic")
    api_key_env = _prompt("API key env var", "ANTHROPIC_API_KEY")
    model = _prompt("Model", "claude-sonnet-4-5-20250929")

    # Verify env var
    if api_key_env in os.environ:
        print(f"    [ok] {api_key_env} is set")
    else:
        print(f"    [warning] {api_key_env} not found in environment")
    print()

    # Step 3: Local Model
    print("Step 3: Local Model")
    print("-" * 40)
    ollama_url = _prompt("Ollama URL", "http://localhost:11434")
    base_model = _prompt("Base model", "llama3.1:8b")
    print()

    # Step 4: Budget
    print("Step 4: Budget")
    print("-" * 40)
    monthly_limit = _prompt("Monthly limit USD", "150.00")
    daily_limit = _prompt("Daily limit USD", "10.00")
    print()

    # Step 5: Generate
    print("Step 5: Generating config...")
    print("-" * 40)

    # Build input/output schema fields
    input_field_list = [f.strip() for f in input_fields.split(",") if f.strip()]

    input_schema_lines = []
    for f in input_field_list:
        input_schema_lines.append(f'    - name: {f}\n      type: string\n      required: true')

    output_schema_lines = []
    for f in output_field_list:
        output_schema_lines.append(f'    - name: {f}\n      type: string\n      required: true')

    match_fields_lines = []
    for f in match_field_list:
        match_fields_lines.append(f'        - name: {f}\n          weight: 1.0\n          case_sensitive: true')

    # Indent prompt template for YAML block scalar
    pt_lines = prompt_template.split("\n")
    pt_yaml = "\n".join(f"      {line}" for line in pt_lines)

    # Build YAML
    config_yaml = f"""# Apprentice Configuration
# Generated by: apprentice init

provider:
  api_base_url: https://api.anthropic.com
  api_key: "env:{api_key_env}"
  model: "{model}"
  timeout_seconds: 30
  max_retries: 3
  retry_base_delay_seconds: 1.0

local_model:
  endpoint: "{ollama_url}"
  model_name: "{base_model}"
  timeout_seconds: 60
  max_retries: 1
  health_check_path: /health

tasks:
  - task_name: {task_name}
    prompt_template: |
{pt_yaml}
    input_schema:
{chr(10).join(input_schema_lines)}
    output_schema:
{chr(10).join(output_schema_lines)}
    evaluators:
      - type: {evaluator_type}
        match_fields:
{chr(10).join(match_fields_lines)}
    thresholds:
      local_ready: 0.7
      local_only: 0.85
      degraded_threshold: 0.3
    sampling_rate_initial: 1.0
    min_training_examples: 100

budget:
  max_daily_cost_usd: {daily_limit}
  max_monthly_cost_usd: {monthly_limit}
  rolling_window_hours: 24
  cost_per_input_token: 0.000003
  cost_per_output_token: 0.000015
  budget_state_path: .apprentice/budget_state.json

finetuning:
  backend: local_lora
  model_base: "{base_model}"
  batch_size: 100
  trigger_interval_hours: 24
  output_dir: .apprentice/models/
  max_concurrent_jobs: 1

audit:
  log_path: .apprentice/audit.log
  log_level: INFO
  log_to_stdout: false
  max_file_size_mb: 100
  backup_count: 5

training_data:
  storage_dir: .apprentice/training_data/
  max_examples_per_task: 50000
"""

    # Create .apprentice directory
    apprentice_dir = Path(".apprentice")
    apprentice_dir.mkdir(parents=True, exist_ok=True)
    (apprentice_dir / "models").mkdir(exist_ok=True)
    (apprentice_dir / "training_data").mkdir(exist_ok=True)

    # Write config
    output = Path(output_path)
    output.write_text(config_yaml)
    print(f"  Config written to: {output}")

    # Validate
    try:
        from apprentice.config_loader import load_config
        load_config(output, env=os.environ)
        print("  Config validation: PASSED")
    except Exception as e:
        print(f"  Config validation: FAILED ({e})")
        print("  You may need to edit the config file manually.")

    print()
    print("=" * 60)
    print(f"  Setup complete!")
    print(f"  Config: {output}")
    print(f"  Next:   apprentice serve --config {output}")
    print("=" * 60)
    print()

    return str(output)
