"""Smoke tests for src/apprentice/remote_api_client.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_remote_api_client():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.remote_api_client")
    assert mod is not None

def test_compute_cost_is_callable():
    """Function compute_cost exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.remote_api_client")
    fn = getattr(mod, "compute_cost", None)
    assert fn is not None, "'compute_cost' not found in apprentice.remote_api_client"
    assert callable(fn)

def test_get_pricing_is_callable():
    """Function get_pricing exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.remote_api_client")
    fn = getattr(mod, "get_pricing", None)
    assert fn is not None, "'get_pricing' not found in apprentice.remote_api_client"
    assert callable(fn)

def test_create_remote_client_is_callable():
    """Function create_remote_client exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.remote_api_client")
    fn = getattr(mod, "create_remote_client", None)
    assert fn is not None, "'create_remote_client' not found in apprentice.remote_api_client"
    assert callable(fn)

def test_send_diversity_request_is_callable():
    """Function send_diversity_request exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.remote_api_client")
    fn = getattr(mod, "send_diversity_request", None)
    assert fn is not None, "'send_diversity_request' not found in apprentice.remote_api_client"
    assert callable(fn)
