"""Smoke tests for src/apprentice/plugin_registry.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_plugin_registry():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.plugin_registry")
    assert mod is not None
