"""Smoke tests for src/apprentice/fine_tuning_orchestrator.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_fine_tuning_orchestrator():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.fine_tuning_orchestrator")
    assert mod is not None

def test_parse_orchestrator_config_is_callable():
    """Function parse_orchestrator_config exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.fine_tuning_orchestrator")
    fn = getattr(mod, "parse_orchestrator_config", None)
    assert fn is not None, "'parse_orchestrator_config' not found in apprentice.fine_tuning_orchestrator"
    assert callable(fn)
