"""Smoke tests for src/apprentice/pii_detection.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_pii_detection():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.pii_detection")
    assert mod is not None
