"""Smoke tests for src/apprentice/training_pipeline.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_training_pipeline():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.training_pipeline")
    assert mod is not None
