"""Smoke tests for src/apprentice/factory.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_factory():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.factory")
    assert mod is not None

def test_build_from_config_is_callable():
    """Function build_from_config exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.factory")
    fn = getattr(mod, "build_from_config", None)
    assert fn is not None, "'build_from_config' not found in apprentice.factory"
    assert callable(fn)
