"""Smoke tests for src/apprentice/event_handler.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_event_handler():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.event_handler")
    assert mod is not None
