"""Smoke tests for src/apprentice/training_data_store.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_training_data_store():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.training_data_store")
    assert mod is not None

def test_initialize_is_callable():
    """Function initialize exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.training_data_store")
    fn = getattr(mod, "initialize", None)
    assert fn is not None, "'initialize' not found in apprentice.training_data_store"
    assert callable(fn)

def test_add_example_is_callable():
    """Function add_example exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.training_data_store")
    fn = getattr(mod, "add_example", None)
    assert fn is not None, "'add_example' not found in apprentice.training_data_store"
    assert callable(fn)

def test_iter_training_examples_is_callable():
    """Function iter_training_examples exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.training_data_store")
    fn = getattr(mod, "iter_training_examples", None)
    assert fn is not None, "'iter_training_examples' not found in apprentice.training_data_store"
    assert callable(fn)

def test_iter_validation_examples_is_callable():
    """Function iter_validation_examples exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.training_data_store")
    fn = getattr(mod, "iter_validation_examples", None)
    assert fn is not None, "'iter_validation_examples' not found in apprentice.training_data_store"
    assert callable(fn)

def test_get_example_count_is_callable():
    """Function get_example_count exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.training_data_store")
    fn = getattr(mod, "get_example_count", None)
    assert fn is not None, "'get_example_count' not found in apprentice.training_data_store"
    assert callable(fn)

def test_get_task_types_is_callable():
    """Function get_task_types exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.training_data_store")
    fn = getattr(mod, "get_task_types", None)
    assert fn is not None, "'get_task_types' not found in apprentice.training_data_store"
    assert callable(fn)
