"""Smoke tests for src/apprentice/observer.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_observer():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.observer")
    assert mod is not None
