"""Smoke tests for src/apprentice/confidence_engine.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_confidence_engine():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.confidence_engine")
    assert mod is not None
