"""Smoke tests for src/apprentice/pii_tokenizer.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_pii_tokenizer():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.pii_tokenizer")
    assert mod is not None
