"""Smoke tests for src/apprentice/report_generator/report_generator.py (auto-generated by pact adopt)."""

import pytest

def test_import_apprentice_report_generator_report_generator():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("apprentice.report_generator.report_generator")
    assert mod is not None

def test_validate_report_config_is_callable():
    """Function validate_report_config exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.report_generator.report_generator")
    fn = getattr(mod, "validate_report_config", None)
    assert fn is not None, "'validate_report_config' not found in apprentice.report_generator.report_generator"
    assert callable(fn)

def test_generate_report_is_callable():
    """Function generate_report exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.report_generator.report_generator")
    fn = getattr(mod, "generate_report", None)
    assert fn is not None, "'generate_report' not found in apprentice.report_generator.report_generator"
    assert callable(fn)

def test_format_report_is_callable():
    """Function format_report exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.report_generator.report_generator")
    fn = getattr(mod, "format_report", None)
    assert fn is not None, "'format_report' not found in apprentice.report_generator.report_generator"
    assert callable(fn)

def test_deliver_webhook_is_callable():
    """Function deliver_webhook exists and is callable."""
    import importlib
    mod = importlib.import_module("apprentice.report_generator.report_generator")
    fn = getattr(mod, "deliver_webhook", None)
    assert fn is not None, "'deliver_webhook' not found in apprentice.report_generator.report_generator"
    assert callable(fn)
